---
- name:
  hosts: all
  become: yes
  tasks:
    - name: remove_new_dir
      file: 
        path: "/home/{{item}}"
        state: absent
      loop:
       - dir1
       - dir2
       - dir3
       - dir4


