---
- name: test
  hosts: all
  become: yes
  tasks:
    - name: create dir
      file:
        path: "/home/{{item}}"
        state: directory
      loop:
        - dir1
        - dir2
        - dir3
        - dir4
